[package]
name = "axum-protobuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
axum = { version = "0.7", default-features = false }
futures-util = { version = "0.3", default-features = false }
prost = { version = "0.12", default-features = false }
serde = { version = "1.0", optional = true, default-features = false }
serde_yaml = { version = "0.9", optional = true }

[features]
default = ["serde"]
serde = [
    "dep:serde",
    "dep:serde_yaml",
    "axum/json"
]